name: assistant
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.11
  - pip==24.0
  - pip:
    - openai
    - azure-identity
    - azure-ai-ml
    - promptflow>=1.10.0
    - promptflow-tools
    - pytest
    - jinja2
    - chainlit
    - tiktoken
    - ipykernel
    - ipython
    - pandas 
    - numpy
